### ISSUE TITLE
Comparing images from image tests

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2506]
Currently the image tests only store a hash of the image, so if an image changes (e.g. due to a new version of Matplotlib, or an intended change on the SunPy side) it's impossible to see what changed. This is a plan to store the test images in another repo, so they are available for comparision.

Todo:

- [x] Make a test image repo (https://github.com/sunpy/sunpy-figure-tests), that contains
    - Test images generated from the master branch 
    - The commit from which the images were generated
- [x] Add a new option to pytest to save the generated images in a suitable local directory [#2507]
- [x] Move the figure tests from Travis to CircleCI (so artifact upload can be used) [#2607]
- [x] Make the figure tests generate a webpage that shows the baseline images (from the image repository), newly generated images, and their visual diff. This can then be uploaded using CircleCI artifacts. [#2681]
- [ ] Create some code that is run at the end of the circle figure builds, that pushes any new images to the repository

**Comment by dpshelio** [comment]
The images repo is at: https://github.com/sunpy/sunpy-figure-tests

For the image comparison we could make Travis to push to a GH pages that shows similar things that GH does when comparing images.

I'm not sure whether the automated cron job would be a good idea. If you check the sunpy-figure-tests repository it has de conda environment that was used to create these images. That I still believe is better to control manually. The reason for thinking as such is because there are different libraries that may affect the change of the figures and we should pin them down to find out when something changes drastically. If done automatically we may not notice when it does change and why it changes.

**Comment by nabobalis** [comment]
Even if it changes drastically, if it still looks ok it, that is fine by me.

**Comment by Cadair** [comment]
All of this should definitely keep the fixed build environment as we do at the moment, the cron job is for updating the figure repo when there is a commit to sunpy that actually changes the figure generation code, not just for random dependency updates.

**Comment by Cadair** [comment]
I also need to modify the Giles config to link to the figure comparison page.

**Comment by wtbarnes** [comment]
What's the status of this? Did that last item ever get finished?

**Comment by Cadair** [comment]
> I also need to modify the Giles config to link to the figure comparison page.

I have done this.

On the topic of auto-push I have been chatting with astrofrog about integrating our own figure test stuff with pytest-mpl, which is the direction I would like to see this go in.

**Comment by dstansby** [comment]
Closing this as the only action left is #3033
