### ISSUE TITLE
Changes after Astropy 3.1

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3154]
This issue is a list of changes that can be made once we drop support for Astropy 3.1 (i.e. depend on Astropy 3.2+)

## Coordinates

- [x] [#3919] Change `get_horizons_coord()` to use `HeliocentricEclipticIAU76` to be more accurate
- ~Change `apparent_longitude()` and `apparent_latitude()` to use `GeocentricTrueEcliptic` (no change in accuracy)~  Using `GeocentricTrueEcliptic` gives incorrect answers, so I need to confirm whether this is a bug in Astropy's definition.  Update: confirmed to be a bug and fixed in astropy/astropy#10129
- [x] [#4005] Remove `try`...`except` blocks for importing `HeliocentricMeanEcliptic` and `GeocentricMeanEcliptic`
- [x] [#4005] Remove the `try`...`except` block for importing `make_transform_graph_docs` in coordinates.
- [x] [#4005] Simplify the [saving/loading example](https://docs.sunpy.org/en/latest/generated/gallery/saving_and_loading_data/coordinates_in_asdf.html) because SkyCoord can be saved

## Visualization

- [ ] `ArrayAnimatorWCS` has a compatibility wrapper for `Quantity.to_string`. [#3407]

**Comment by ayshih** [comment]
> * Change `get_horizons_coord()` to use `HeliocentricEclipticIAU76` to be more accurate

I finally checked, and making this change decreases the discrepancy for the position of Earth from tens of kilometers to a few kilometers.  If I also make Astropy use a JPL ephemeris rather than its built-in ephemeris, the discrepancy drops to below a *meter* (not kilometer).

**Comment by Cubostar** [comment]
Does this still need to be done? I can work on this.

**Comment by ayshih** [comment]
@Cubostar This will need to be done, but not now.  We need to wait until SunPy depends on Astropy 3.2, and there isn't a compelling reason yet to bump up the dependency.

**Comment by Cadair** [comment]
@ayshih I have hijacked this for all Astropy 3.1 compatibility changes.

**Comment by Cadair** [comment]
I think we have decided that we are 3.2+ for 2.0 right? If so we should make all these changes?
