### ISSUE TITLE
Properly support velocities in our coordinate frames

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3188]
Stuff to do:

- [x] Fix the Astropy bug with the HCRS<->ICRS transformations (astropy/astropy#8794)
- [x] Re-implement all of our transformations away from `FunctionTransform`.  ~I'm thinking that HGS<->HGC and HGS<->HCC transformations will be `DynamicMatrixTransform`, and HCC<->HPC and all loopback transformations will be `FunctionTransformWithFiniteDifference`.~  The transformations that I was thinking to implement as `DynamicMatrixTransform` actually have an origin shift if transforming between different observation times.  While they could technically be `AffineTransform`s, it's probably more tractable to make them all `FunctionTransformWithFiniteDifference`. (#3247)
- [x] Fix the missing induced-velocity component for the HCRS<->HGS transformations (#3247)
- [x] Define `default_differential` (and maybe `frame_specific_representation_info`) for each of our frames (#4102)
- [x] Add documentation and guide (#4610)
- [x] Convert HCRS<->HGS transformation `FunctionTransformWithFiniteDifference` to fix the fact that `AffineTransform` can't account for an induced angular velocity (#4613)
