### ISSUE TITLE
Add a "What's New" entry for 5.1 release

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#7258]
### Provide a general description of the issue or problem.

We need a "What's New" entry for v5.1. We have not been adding "What's New" entries as we go so we'll need to do this all in one go. Below is a running list of the PRs that need them:

- [x] GONG Map class (#7220)
- [x] `is_visible` method (#7118)
- ~~Deprecated `sunpy.coordinates.transformations` (#7113)~~
- [x] SPICE coords (#7237)
- [ ] Magnetic coords (#7239)
- [x] WISPR map improvements (#7180)

We have a lot of removals of previously deprecated things in this release. Not sure we also want to include a "Things we removed" section that just lists all of those.
